/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Always available and unauthenticated. Reports that the process is up and whether the other operations require the access token, so a client can ask for the token before making any gated request (the mDNS TXT record already advertises the same auth=token flag). Use /status for real state.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Appliance status
         * @description Appliance-level runtime state: version, uptime, RTSP listener, discovery, whether an access token is required, and per-device counts. Full per-device detail lives at /devices.
         */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List capture devices
         * @description Every configured device with its configured and negotiated parameters and runtime state, including devices that failed to open (state "skipped") or died after startup (state "failed").
         */
        get: operations["listDevices"];
        put?: never;
        /**
         * Enable (provision) a detected capture device
         * @description Enables streaming on a capture device the host exposes but the configuration does not yet list. The appliance derives a unique name from the device's hardware label, generates a hard-to-guess RTSP path, and chooses a mode, sample rate and channel count from the device's probed capabilities (Opus 48 kHz mono when supported, otherwise raw PCM at the device's best rate). Any field set in the request overrides its derived default. The change is persisted and hot-applied to the running pipeline; the new device starts serving without a restart.
         */
        post: operations["provisionDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List detected but unconfigured capture devices
         * @description Every capture device the host exposes that the configuration does not yet list, with the sample rates and channel counts probed for it. These are the devices an operator can enable from the web UI without editing the configuration by hand.
         */
        get: operations["listAvailableDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one capture device
         * @description The named device with its configuration and runtime state.
         */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        /**
         * Remove a configured capture device
         * @description Removes the named device from the configuration, stopping it if it is serving and returning its hardware to the pool of available devices. The change is persisted and hot-applied without a restart.
         */
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live event stream
         * @description A single multiplexed Server-Sent Events stream for the whole
         *     appliance. Each SSE event's `event:` field names its type and its
         *     `data:` field is a JSON document:
         *
         *     - `levels`: emitted at a fixed cadence (10 Hz) with one
         *       LevelsEvent covering every serving device. Peak and RMS are
         *       measured over the window since the previous event; meter
         *       ballistics (decay, peak hold) are the client's job.
         *     - `notification`: emitted when a notification is raised, with one
         *       Notification as data. The stream is best effort: there is no replay,
         *       `Last-Event-ID` is ignored, and a client re-syncs from GET
         *       /notifications on connect, on reconnect, and whenever it detects an
         *       id gap. An active condition's onset whose title or message changed
         *       while it stayed active is sent again under its own id; a client
         *       replaces the entry it holds with that id (it is not a new entry).
         *     - `heartbeat`: emitted every 15 seconds with `{}` as data, so
         *       idle connections stay alive and clients can detect a dead
         *       server. Sent as a named event (not an SSE comment) so simple
         *       fetch-based parsers see it.
         *
         *     The stream opens with an SSE comment line (`: open`) once the
         *     server has subscribed to the requested events; clients ignore it,
         *     as the SSE format asks, or may take it as the stream being up.
         *
         *     Further event types will be added additively; clients must ignore
         *     event types they do not know. Level data is ephemeral: there is no
         *     replay and `Last-Event-ID` is ignored.
         *
         *     Browser note: the native EventSource API cannot send an
         *     Authorization header, so an authenticated web client should
         *     consume this endpoint with fetch and a streamed response body.
         *
         *     OpenAPI 3.1 cannot type per-event payloads on a stream; the
         *     `data:` schema for `levels` events is LevelsEvent. This operation
         *     moves to OpenAPI 3.2 `itemSchema` once the code generators
         *     support it.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notifications
         * @description The current notification snapshot: the boot identity, the server's wall-clock time and uptime read at one instant, the ring depth, the next id that will be assigned, and every discrete history entry still in the ring merged with every active condition (even ones the ring has trimmed), in ascending id order. Clients bootstrap and re-sync from this; the /events stream is best effort, so a gap in streamed ids means a dropped event and the client refetches here. The ring keeps the most recent 500 history entries in memory only: there is no time-based expiry, and a restart (a new bootId) starts it empty. A full snapshot runs to about 165 KB of JSON, so the response is gzip-compressed when the request's Accept-Encoding allows it.
         */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the running configuration
         * @description The configuration as loaded (defaults applied). This includes the shared access token, which only an authenticated caller can read (this route is behind the bearer gate when a token is set); the Access Control card needs it to show what to paste into BirdNET-Go.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update configuration
         * @description Validates and persists a partial configuration update to the config file. Changes are applied to the running appliance in place when possible (a token or discovery change, and adding, removing or restarting a device); `restartRequired` in the response reports the exception, when a change could only be persisted and needs a restart to take effect.
         */
        patch: operations["patchConfig"];
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Host system information
         * @description Static hardware facts (platform, CPU, total memory and storage) and live host metrics (CPU and memory use, SoC temperature where a sensor exists), plus per-interface network details, for the web UI's host panel.
         */
        get: operations["getSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an appliance restart
         * @description Requests a graceful shutdown and restart of the appliance process. The server responds 202 Accepted, flushes in-flight responses, and initiates a graceful exit.
         */
        post: operations["postSystemRestart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Install the available update
         * @description Starts a one-button update to the newest release the last check found. The appliance downloads the release for its platform, checks its size and SHA-256 against the signed manifest, and hands it to the root updater, which verifies it again, installs it, and restarts the appliance (dropping connected RTSP clients briefly). A new version that does not come up is rolled back automatically. The response returns at once with the update in the downloading phase; progress and the outcome arrive as notifications and in `GET /system`. Only a `remote-mic service install` installation with the root updater units can update itself (`update.canApply`).
         */
        post: operations["postSystemUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/update/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check for an update now
         * @description Checks for a newer release immediately instead of waiting for the daily check, and returns the result. A check that finished in the last few seconds is returned without asking again. A failed check is not an error response: it is reported in `lastError`.
         */
        post: operations["postSystemUpdateCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Management TLS certificate metadata
         * @description Public metadata for the certificate the management listener presents: subject, issuer, whether it is self-signed, its subject alternative names, its validity window, and its SHA-256 fingerprint. Never returns private key material. Use it to verify the certificate before trusting it, and /system/certificate/pem to import it into a client trust store.
         */
        get: operations["getSystemCertificate"];
        /**
         * Install a custom management TLS certificate
         * @description Replace the management listener's certificate with an operator-supplied certificate and private key. The pair is validated first (the key matches the certificate, it is currently valid, it carries a subject alternative name, and it is usable for server authentication); nothing is written on a validation failure. On success the pair is persisted to the certificate directory and served to new TLS connections at once, without a restart; connections already open keep the previous certificate until they reconnect. The installed certificate is pinned, so the appliance never regenerates it automatically. The private key is never returned by any endpoint. A browser may warn on its next load until the new certificate is trusted.
         */
        put: operations["putSystemCertificate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/certificate/pem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the management TLS certificate (PEM)
         * @description The management listener's certificate, PEM-encoded, so an operator can import it into a client trust store. This is the public certificate only; the private key is never exposed.
         */
        get: operations["getSystemCertificatePem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/certificate/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate the self-signed management certificate
         * @description Generate a fresh self-signed certificate for the management listener and serve it to new TLS connections at once, without a restart. It always covers the auto-detected names (loopback, the hostname, the hostname.local mDNS name, and the LAN IP addresses); any extraSans are added on top. This replaces a previously installed custom certificate and clears its pin, returning the appliance to self-managed certificates. Connections already open keep the previous certificate until they reconnect, and a browser may warn on its next load until the new certificate is trusted.
         */
        post: operations["regenerateSystemCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Liveness probe response. */
        Health: {
            /** @constant */
            status: "ok";
            /**
             * @description Appliance build version.
             * @example v0.3.0
             */
            version: string;
            /**
             * @description True when every other operation requires the access token.
             * @example true
             */
            authRequired: boolean;
        };
        /** @description Appliance-level runtime state. */
        ApplianceStatus: {
            /** @description Appliance build version (set at build time). */
            version: string;
            /**
             * Format: int64
             * @description Seconds since the process started.
             */
            uptimeSeconds: number;
            /**
             * @description The RTSP listener address (host:port as configured).
             * @example :8554
             */
            rtspListen: string;
            /** @description Whether mDNS/DNS-SD advertisement is on. */
            discoveryEnabled: boolean;
            /** @description Whether a shared access token is configured, so the API, web UI and RTSP stream require credentials. */
            authRequired: boolean;
            /** @description Devices currently capturing and serving their track. */
            devicesServing: number;
            /** @description Devices in the configuration, whatever their state. */
            devicesTotal: number;
            /** @description Serve-time CLI flag overrides in force for this run. Each entry names a config field whose effective (running) value differs from the persisted config file value because a serve flag (--listen, --mgmt-listen, --cert-dir, --management, --discovery) overrode it. Absent or empty when no serve overrides are active. */
            overrides?: components["schemas"]["ConfigOverride"][];
        };
        /** @description One config field overridden by a serve CLI flag for this run. The effective value is in force now; the persisted value is what the config file holds and what a restart without the flag would use. */
        ConfigOverride: {
            /**
             * @description Dotted config path of the overridden field.
             * @example listen
             * @example management.listen
             */
            field: string;
            /** @description Value in force for this run (from the serve flag). */
            effective: string;
            /** @description Value stored in the config file. */
            persisted: string;
        };
        /** @description Public metadata for the management listener's TLS certificate. Never includes private key material. */
        CertificateInfo: {
            /**
             * @description Certificate subject distinguished name.
             * @example CN=birdnet-go-remote-mic
             */
            subject: string;
            /** @description Certificate issuer distinguished name. */
            issuer: string;
            /** @description Whether the certificate is self-signed (subject equals issuer). */
            selfSigned: boolean;
            /** @description Subject alternative name DNS entries. */
            dnsNames: string[];
            /** @description Subject alternative name IP entries. */
            ipAddresses: string[];
            /**
             * Format: date-time
             * @description Start of the certificate validity window.
             */
            notBefore: string;
            /**
             * Format: date-time
             * @description End of the certificate validity window.
             */
            notAfter: string;
            /**
             * @description SHA-256 fingerprint of the DER certificate, colon-separated uppercase hex.
             * @example AB:CD:EF
             */
            fingerprintSha256: string;
            /** @description Whether the appliance manages this certificate (a self-signed certificate it generated and will regenerate on an address change or expiry). False when an operator installed a custom certificate, which the appliance then never replaces automatically. */
            managed: boolean;
        };
        /** @description A custom certificate and its private key to install on the management listener. Validated before anything is written; on success the pair is persisted and served to new TLS connections without a restart. The private key is write-only and never returned by any endpoint. */
        CertificateInstallRequest: {
            /**
             * @description PEM-encoded certificate, leaf first, with any intermediate chain certificates after it. Must carry at least one subject alternative name and be valid now (not expired and not before its start).
             * @example -----BEGIN CERTIFICATE-----
             *     ...
             *     -----END CERTIFICATE-----
             */
            certPem: string;
            /**
             * Format: password
             * @description PEM-encoded unencrypted private key matching the certificate (PKCS#8, PKCS#1 RSA, or SEC1 EC). Write-only: never returned by any endpoint.
             */
            keyPem: string;
        };
        /** @description Options for regenerating the self-signed management certificate. The regenerated certificate always covers the auto-detected names (loopback, the hostname, the hostname.local mDNS name, and the LAN IP addresses); extraSans adds further names on top. */
        CertificateRegenerateRequest: {
            /** @description Extra DNS names or IP addresses to add to the subject alternative names, for names the auto-detection cannot see. */
            extraSans?: string[];
        };
        /** @description One configured capture device: its configuration, what capture actually negotiated, and its runtime state. */
        Device: {
            /**
             * @description Unique device name (also the DNS-SD instance name).
             * @example garden
             */
            name: string;
            /**
             * @description Configured capture device id. A stable id names the physical device and survives reboots: a USB unit by vendor, product and serial follows it to any port, while the by-port form (a USB unit with no serial) and the alsa-lib hw:CARD= form survive a replug into the same port. A card-index id such as hw:1,0 is accepted but can name a different device after a reboot (see idStable).
             * @example usb:1235:8218:s=S1A2B3:if=0,0
             * @example hw:CARD=Loopback,DEV=1
             */
            device: string;
            /**
             * @description Current-boot ALSA address the configured id resolved to, for display. Absent when the id names no present hardware. It changes across reboots and replugs and is never persisted.
             * @example hw:4,0
             */
            hwAddr?: string;
            /**
             * @description False when the configured id names a card by its kernel index (hw:N,D), which the kernel assigns in probe order, so the id can point at a different device after a reboot or replug.
             * @example true
             */
            idStable?: boolean;
            /**
             * @description RTSP path serving this device.
             * @example /garden
             */
            path: string;
            mode: components["schemas"]["StreamMode"];
            /**
             * @description Sample format (only S16LE is supported).
             * @constant
             */
            format: "s16";
            /** @description Requested capture sample rate in Hz (as configured). */
            rate: number;
            /** @description Selected 1-based capture channel numbers to stream, ascending and unique (e.g. [1], [1, 2], or [1, 3]). The stream carries these channels in order; a single-channel selection yields a mono stream. Opus accepts one channel (mono) or two (stereo); PCM L16 carries any selection. */
            channels: number[];
            /**
             * @description Every 1-based capture channel that at least one of the device's streams carries, ascending and unique: the union of the stream selections, where channels describes only the first stream. The UI marks these channels as live on the level meters.
             * @example [
             *       1
             *     ]
             * @example [
             *       1,
             *       3
             *     ]
             */
            streamedChannels?: number[];
            opus?: components["schemas"]["OpusSettings"];
            state: components["schemas"]["DeviceState"];
            /** @description Sample rate the hardware actually delivers. Absent unless the device opened (the appliance refuses a rate mismatch, so when present it equals rate). */
            negotiatedRate?: number;
            /** @description Channel count the hardware actually delivers. Absent unless the device opened. */
            negotiatedChannels?: number;
            /** @description Hardware capture sample format the device negotiated, as a short token (s16, s24_le, s24_3le, or s32). Absent unless the device opened. The stream is always delivered as S16LE, so a wider capture format means the audio is downconverted to 16-bit; this surfaces that reduction. */
            negotiatedFormat?: string;
            /** @description Whether at least one RTSP client is playing one of this device's streams. Always false for skipped or failed devices. */
            clientConnected: boolean;
            /** @description How many RTSP clients are playing this device's streams right now, summed over its streams (each stream serves up to 8 at once). Zero for skipped or failed devices. */
            clientCount: number;
            /**
             * Format: int64
             * @description Audio dropped because a client or the encoder was not keeping up (a client's drop counts once per client per dropped frame; the encoder's once per dropped capture period). Zero for devices that never served.
             */
            droppedFrames: number;
            /**
             * Format: int64
             * @description Capture overruns (ALSA xruns) the device's capture has recovered from since it was last opened. Each one lost audio for every stream on the device, before any client saw it, and usually means the host was too busy or the USB connection is unstable; a recovered system suspend counts as one too. The count starts from zero each time the device is opened. A failed device keeps reporting the count it reached; a device with no open capture (never opened, disabled, or skipped after a failed reopen) reports zero, so treat a decrease as a reset.
             */
            overruns: number;
            /** @description Why the device is skipped or failed. Absent when serving. */
            error?: string;
            /**
             * @description Machine-readable class of why a skipped or failed device is not serving, so a client can title the failure without parsing `error`: its id names no connected hardware (not-connected), several identical units (ambiguous), or is malformed; resolving it failed (resolve-failed); another device already captures from the same hardware (same-hardware); the capture open failed (open-failed); or a serving device stopped because it was unplugged (disconnected) or for a reason not confirmed as an unplug (failed). Absent while serving, when disabled, from an older appliance, and in the provisional record POST /devices returns when the new device has not been applied yet. Clients must tolerate values added later.
             * @enum {string}
             */
            downCause?: "not-connected" | "ambiguous" | "malformed" | "resolve-failed" | "same-hardware" | "open-failed" | "disconnected" | "failed";
            /**
             * @description Human-facing label derived from the sound card name (the text before the first comma). Absent when the device id resolved to no present hardware, or the derived label is empty. The UI uses it to default a blank name.
             * @example Scarlett 2i2 USB
             */
            friendlyName?: string;
            /**
             * @description Sample rates the hardware accepts, from the last successful probe (re-probed each time the device is opened, and retained across a transiently-unprobeable open). Absent or empty when no probe has succeeded (device missing or busy), in which case the UI offers a static list of common rates.
             * @example [
             *       48000,
             *       96000,
             *       192000
             *     ]
             */
            supportedRates?: number[];
            /**
             * @description Channel counts the hardware accepts, from the last successful probe (re-probed each time the device is opened) via the same non-blocking capability query as supportedRates. Absent or empty when no probe has succeeded (device missing or busy), in which case the UI offers a mono/stereo default. The UI takes the largest count as the number of selectable channels and builds the per-channel selection control (Ch1..ChN) from it.
             * @example [
             *       2
             *     ]
             * @example [
             *       1,
             *       2
             *     ]
             * @example [
             *       2,
             *       4
             *     ]
             */
            supportedChannels?: number[];
            /** @description Per-stream runtime state, one entry per stream fanned out from this device's shared capture. Present only while the device is serving. The device-level clientConnected, clientCount and droppedFrames aggregate these (any client connected; summed clients; summed drops), so a client that predates fan-out can ignore this array. A single-stream device carries one entry mirroring the device-level fields. */
            streams?: components["schemas"]["StreamStatus"][];
        };
        /** @description One stream's runtime state within a serving device. */
        StreamStatus: {
            /**
             * @description RTSP path serving this stream.
             * @example /garden
             */
            path: string;
            /** @description Whether at least one RTSP client is playing this stream. */
            clientConnected: boolean;
            /** @description How many RTSP clients are playing this stream right now, up to 8. */
            clientCount: number;
            /**
             * Format: int64
             * @description Audio dropped for this stream because a client or the encoder was not keeping up (a client's drop counts once per client per dropped frame; the encoder's once per dropped capture period). Zero when it never fell behind.
             */
            droppedFrames: number;
        };
        /**
         * @description serving: capturing and available over RTSP. skipped: not opened (the device is not connected, its id matches several devices, it resolves to hardware another entry already captures from, or the open failed); error says why. failed: died after opening; its RTSP path returns 404 until the device restarts. disabled: configured but intentionally not opened (its enabled flag is false); not captured or streamed until re-enabled, which is hot-applied without a restart. Recovery of a skipped or failed device: one bound by a stable id that could not be opened, or failed, while still present is retried automatically with a growing delay; one that was unplugged restarts when it is reconnected; a card-index id restarts only on a config save.
         * @enum {string}
         */
        DeviceState: "serving" | "skipped" | "failed" | "disabled";
        /** @description A capture device the host exposes that the configuration does not yet list. It carries only the device id and the probed capabilities; a name, path and stream parameters are assigned when it is provisioned (see POST /devices). */
        AvailableDevice: {
            /**
             * @description Capture device id to persist, as provisioning stores it. It is a stable id that survives reboots (a serial-form id follows the unit to any port; a by-port or hw:CARD= id survives a replug into the same port), unless idStable is false.
             * @example usb:1235:8218:s=S1A2B3:if=0,0
             */
            device: string;
            /**
             * @description Current-boot ALSA address of the device, for display only.
             * @example hw:4,0
             */
            hwAddr?: string;
            /**
             * @description False when the host offered no stable id for this device (for example no sysfs in a minimal container, or a USB device with neither a serial nor a derivable port), in which case device is a card index that can change across reboots.
             * @example true
             */
            idStable?: boolean;
            /**
             * @description Always "available"; the device is detected but not configured.
             * @constant
             */
            state: "available";
            /**
             * @description Human-facing label derived from the sound card name.
             * @example Scarlett 2i2 USB
             */
            friendlyName?: string;
            /**
             * @description Sample rates the hardware accepts, verified with a real HW_PARAMS commit. Absent or empty when the device could not be probed.
             * @example [
             *       48000,
             *       96000,
             *       192000
             *     ]
             */
            supportedRates?: number[];
            /**
             * @description Channel counts the hardware accepts. Absent or empty when the device could not be probed. The UI takes the largest count as the number of selectable channels (Ch1..ChN).
             * @example [
             *       2
             *     ]
             * @example [
             *       1,
             *       2
             *     ]
             * @example [
             *       2,
             *       4
             *     ]
             */
            supportedChannels?: number[];
        };
        /** @description Request to enable (provision) a detected capture device. Only device is required; the appliance derives sensible defaults for everything else, and any field set here overrides its derived default. */
        ProvisionDeviceRequest: {
            /**
             * @description Capture device id to enable, as reported by GET /devices/available.
             * @example usb:1235:8218:s=S1A2B3:if=0,0
             */
            device: string;
            /** @description Optional unique device name; derived from the hardware label when omitted. */
            name?: string;
            mode?: components["schemas"]["StreamMode"];
            /** @description Optional capture sample rate in Hz; chosen from the device's capabilities when omitted. */
            rate?: number;
            /** @description Optional 1-based channel selection to stream, ascending and unique. When omitted the appliance selects a single channel: it captures briefly from the device and picks the loudest channel (the lowest numbered among channels within 1 dB of the loudest, and channel 1 when all are near silence or the measurement fails). An empty array is treated the same as omitting the field (so no minItems is imposed). */
            channels?: number[];
        };
        /**
         * @description pcm streams raw L16 at the capture rate (the ultrasonic path); opus streams 48 kHz Opus, mono or stereo (one or two channels; the normal-audio path).
         * @enum {string}
         */
        StreamMode: "pcm" | "opus";
        /** @description Opus encoder settings, used only when mode is opus. */
        OpusSettings: {
            /** @description Encoder bitrate in bits per second; 0 selects the default of 128 kbps per channel carried (128 kbps mono, 256 kbps stereo), capped at the 510 kbps Opus maximum. An explicit value above 510000 is rejected. */
            bitrate?: number;
        };
        /** @description The payload of one `levels` SSE event: audio levels for every serving device, measured over the window since the previous event. */
        LevelsEvent: {
            devices: components["schemas"]["DeviceLevels"][];
        };
        /** @description One device's audio levels over the last measurement window, one entry per captured channel. A mono device carries a single-element channels array; a stereo (or higher) device carries one entry per interleaved channel. */
        DeviceLevels: {
            /**
             * @description The device's configured unique name.
             * @example garden
             */
            name: string;
            /** @description Per-channel levels, ordered by capture channel index. */
            channels: components["schemas"]["ChannelLevels"][];
        };
        /** @description One capture channel's audio levels over the last window. */
        ChannelLevels: {
            /**
             * @description Zero-based capture channel index.
             * @example 0
             */
            channel: number;
            /**
             * Format: double
             * @description Peak sample level in dBFS over the window. Silence is clamped to the -99 floor.
             * @example -12.4
             */
            peakDbfs: number;
            /**
             * Format: double
             * @description RMS level in dBFS over the window, clamped to the -99 floor.
             * @example -27.9
             */
            rmsDbfs: number;
            /** @description Whether any sample in the window hit full scale. */
            clipped: boolean;
        };
        /**
         * @description error is a fault needing attention; warning is a degraded state; info is routine. Only error notifications raise a client toast.
         * @enum {string}
         */
        NotificationSeverity: "error" | "warning" | "info";
        /**
         * @description The subsystem a notification concerns.
         * @enum {string}
         */
        NotificationCategory: "device" | "audio" | "stream" | "system" | "config";
        /**
         * @description event is a discrete one-off; onset marks a condition becoming active and clear marks it becoming inactive, paired by key.
         * @enum {string}
         */
        NotificationKind: "event" | "onset" | "clear";
        /** @description One notification entry. */
        Notification: {
            /**
             * Format: int64
             * @description Monotonic per-boot id, assigned in publish order.
             * @example 42
             */
            id: number;
            /**
             * @description Identity of the process run that produced this entry. Ids restart at 1 each boot, so a client resets its read state when bootId changes.
             * @example 4a2b1c8e9f0d3e5a
             */
            bootId: string;
            /**
             * Format: date-time
             * @description When the entry was published (appliance wall clock). An appliance without a real-time clock can step this clock by hours when NTP first syncs, so entries published before the step carry a wrong time; uptimeMs does not have that problem.
             * @example 2026-09-12T11:03:00Z
             */
            time: string;
            /**
             * Format: int64
             * @description Milliseconds since the notification center started (early in process startup), read from a monotonic clock that a wall-clock step does not move. The difference between two entries' uptimeMs is the true time between them, and the snapshot's uptimeMs gives the uptime at a known moment, so a client can place any entry relative to when it received the snapshot.
             * @example 93500
             */
            uptimeMs: number;
            severity: components["schemas"]["NotificationSeverity"];
            category: components["schemas"]["NotificationCategory"];
            kind: components["schemas"]["NotificationKind"];
            /**
             * @description Condition identity, present on onset and clear entries and absent on discrete events. A clear pairs with its onset by key.
             * @example device:garden:down
             */
            key?: string;
            /**
             * @description The subject (device name, RTSP path, or remote address).
             * @example garden
             */
            source?: string;
            /**
             * @description Short noun label.
             * @example Device failed
             */
            title: string;
            /** @description One-sentence detail naming the specific device, path or value. */
            message: string;
        };
        /** @description The full current notification state a client bootstraps and re-syncs from. */
        NotificationSnapshot: {
            /**
             * @description Identity of the current process run.
             * @example 4a2b1c8e9f0d3e5a
             */
            bootId: string;
            /**
             * Format: date-time
             * @description The appliance's wall-clock time when the snapshot was taken. It is informational: an appliance without a real-time clock can step it, so place entries in time from uptimeMs rather than from wall times.
             * @example 2026-09-12T11:03:00Z
             */
            serverTime: string;
            /**
             * Format: int64
             * @description The notification center's uptime in milliseconds at the same instant as serverTime. An entry happened (uptimeMs minus the entry's uptimeMs) milliseconds before the snapshot, whatever its wall-clock time says.
             * @example 120000
             */
            uptimeMs: number;
            /**
             * @description How many history entries the ring keeps. Ids below nextId minus capacity have been trimmed, except onsets of conditions that are still active, which stay pinned.
             * @example 500
             */
            capacity: number;
            /**
             * Format: int64
             * @description The id the next published notification will take. A streamed id at or beyond a previously seen nextId with earlier ids missing means a dropped event; the client refetches this snapshot.
             * @example 43
             */
            nextId: number;
            /** @description History and active conditions, ascending by id. */
            notifications: components["schemas"]["Notification"][];
        };
        /** @description The appliance configuration (defaults applied). */
        Config: {
            /** @description RTSP listener address (host:port). */
            listen: string;
            discovery: components["schemas"]["DiscoverySettings"];
            management: components["schemas"]["ManagementSettings"];
            auth: components["schemas"]["AuthSettings"];
            notifications: components["schemas"]["NotificationSettings"];
            updates: components["schemas"]["UpdateSettings"];
            devices: components["schemas"]["DeviceConfig"][];
        };
        /** @description The configuration of one device, without runtime state. A device opens one capture and fans it out into one or more streams. The flat path, mode, channels and opus fields describe the device's FIRST stream, so a client that predates fan-out still configures a single-stream device; the full set is in streams. On a PATCH, a body carrying streams is authoritative and the flat fields are ignored; a body omitting streams defines a single stream from the flat fields, and is rejected when it would collapse an existing multi-stream device. The maxLength limits on name, device and path apply to values a write introduces; a value already in the config file (which loads without them) may exceed them in a response. */
        DeviceConfig: {
            name: string;
            device: string;
            path: string;
            mode: components["schemas"]["StreamMode"];
            rate: number;
            /** @description Selected 1-based capture channel numbers to stream, ascending and unique (e.g. [1], [1, 2], or [1, 3]). */
            channels: number[];
            /** @constant */
            format: "s16";
            opus?: components["schemas"]["OpusSettings"];
            /** @description Whether this device is captured and streamed; defaults to true when absent. Set false to keep it configured but not opened. A change is hot-applied without a restart. */
            enabled?: boolean;
            /** @description Whether this device raises the very-quiet audio condition; defaults to true when absent. Set false for a device expected to be silent for long stretches (a bat microphone by day). Stuck-at-zero and clipping conditions are unaffected. */
            quietAlert?: boolean;
            /** @description The streams fanned out from this device's shared capture, one RTSP path each. When present it is authoritative and the flat path/mode/channels/opus fields are ignored (they mirror streams[0] for older clients). One capture is opened per device, so every stream shares the device rate and format. */
            streams?: components["schemas"]["StreamConfig"][];
        };
        /** @description One stream fanned out from a device's shared capture: a subset of the device's channels, encoded in one mode, served at one RTSP path. */
        StreamConfig: {
            /**
             * @description RTSP path serving this stream; unique across every device's streams. The maxLength applies to a path a write introduces (see DeviceConfig).
             * @example /garden
             */
            path: string;
            mode: components["schemas"]["StreamMode"];
            /** @description Selected 1-based capture channel numbers this stream carries, ascending and unique (e.g. [1], [1, 2], or [1, 3]). Opus accepts one channel (mono) or two (stereo); PCM L16 carries any selection. */
            channels: number[];
            opus?: components["schemas"]["OpusSettings"];
        };
        /** @description mDNS/DNS-SD advertisement settings. */
        DiscoverySettings: {
            /** @description mDNS/DNS-SD advertisement; defaults to true when absent. In a patch, an absent field (including an empty discovery object) leaves discovery unchanged, mirroring AuthSettings.token. */
            enabled?: boolean;
        };
        /** @description Shared access token settings. The one token gates the management API and web UI (bearer) and the RTSP stream (Digest password). */
        AuthSettings: {
            /**
             * @description The shared access token: 12 to 128 characters from the URL unreserved set [A-Za-z0-9._~-], or empty for open access. In a patch, an absent field leaves the token unchanged and an empty string disables authentication. Reads return the configured value (empty when open) to the authenticated caller.
             * @example k7Qm3vX9pL2wR8nT
             */
            token?: string;
        };
        /** @description HTTPS management API settings. */
        ManagementSettings: {
            /** @description Whether the management API is served; defaults to true when absent. */
            enabled?: boolean;
            /**
             * @description HTTPS listen address (host:port); defaults to :8443.
             * @example :8443
             */
            listen?: string;
            /** @description Directory where the self-signed certificate and key are persisted; defaults to the config file's directory. */
            certDir?: string;
        };
        /** @description Condition-monitor settings behind the notification center. In a read every field is materialized to its effective value; in a patch an absent field (or an absent nested object) leaves the current value unchanged, so a partial block like {"host":{"cpuPercent":95}} touches only that field. */
        NotificationSettings: {
            /** @description Whether the condition monitors run; defaults to true when absent. Disabling them stops the audio-signal and host-health conditions but leaves device-failure, client and config events publishing. */
            enabled?: boolean;
            audio?: components["schemas"]["AudioAlertSettings"];
            host?: components["schemas"]["HostAlertSettings"];
        };
        /** @description Release update check settings. */
        UpdateSettings: {
            /** @description Whether the appliance checks daily for a newer release; defaults to true when absent. With it off the appliance makes no outbound update request at all. In a patch, an absent field leaves the setting unchanged. */
            check?: boolean;
        };
        /** @description Audio-signal condition thresholds. */
        AudioAlertSettings: {
            /** @description Peak level below which the input counts as very quiet (dBFS). Default -60. */
            quietDbfs?: number;
            /** @description Seconds below quietDbfs before the very-quiet warning raises. Default 600. */
            quietSeconds?: number;
            /** @description Seconds at digital zero before the no-signal warning raises. Default 30. */
            zeroSeconds?: number;
            /** @description Percentage of clipped windows within the clip window that raises the clipping warning. Default 20. */
            clipPercent?: number;
            /** @description Window in seconds over which clipping is measured. Default 10. */
            clipWindowSeconds?: number;
        };
        /** @description Host-health condition thresholds. Each clear threshold must sit below its onset to keep a hysteresis gap (a clear at or above the onset would chatter the condition). */
        HostAlertSettings: {
            /** @description CPU usage percent that raises the warning. Default 90. */
            cpuPercent?: number;
            /** @description CPU usage percent below which the warning clears; must be below cpuPercent. Default 75. */
            cpuClearPercent?: number;
            /** @description Temperature in Celsius that raises the warning. Default 80. */
            tempCelsius?: number;
            /** @description Temperature in Celsius below which the warning clears; must be below tempCelsius. Default 75. */
            tempClearCelsius?: number;
            /** @description Disk-used percent that raises the warning. Default 90. */
            diskPercent?: number;
            /** @description Disk-used percent below which the warning clears; must be below diskPercent. Default 85. */
            diskClearPercent?: number;
            /** @description Available-memory percent below which the warning raises. Default 10. */
            memFreePercent?: number;
            /** @description Available memory in MiB below which the warning raises. Default 64. */
            memFreeMiB?: number;
        };
        /** @description A partial configuration update. Only the fields present are changed; the result must validate as a whole configuration. */
        ConfigPatch: {
            discovery?: components["schemas"]["DiscoverySettings"];
            auth?: components["schemas"]["AuthSettings"];
            notifications?: components["schemas"]["NotificationSettings"];
            updates?: components["schemas"]["UpdateSettings"];
            /** @description Replaces the whole device list when present (per-device merge is not supported). An empty array removes every device, matching Config.devices, which also imposes no minItems. */
            devices?: components["schemas"]["DeviceConfig"][];
        };
        /** @description Outcome of a persisted configuration update. */
        ConfigUpdateResult: {
            config: components["schemas"]["Config"];
            /** @description True when the persisted change only takes effect after the appliance restarts. */
            restartRequired: boolean;
        };
        /** @description Acknowledgement that a restart request was accepted. */
        RestartResult: {
            /**
             * @description Status message confirming restart initiation.
             * @example restarting
             */
            status: string;
        };
        /** @description RFC 9457 problem details. */
        Problem: {
            /**
             * Format: uri-reference
             * @default about:blank
             */
            type: string;
            title?: string;
            status?: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
        };
        /** @description A problem detail carrying per-field validation errors. */
        ValidationProblem: components["schemas"]["Problem"] & {
            errors?: {
                /**
                 * @description Dotted path of the invalid field.
                 * @example devices[0].rate
                 */
                field: string;
                reason: string;
            }[];
        };
        /** @description Host hardware facts and live system metrics. */
        SystemInfo: {
            /**
             * @description Go platform tag, GOOS/GOARCH.
             * @example linux/arm64
             */
            platform: string;
            /**
             * @description Operating system pretty name (from /etc/os-release).
             * @example Debian GNU/Linux 13 (trixie)
             */
            os?: string;
            /**
             * @description Kernel release string.
             * @example 6.6.20+rpt-rpi-2712
             */
            kernel?: string;
            /**
             * @description The host's name.
             * @example birdmic
             */
            hostname: string;
            /**
             * @description CPU or SoC model as reported by the kernel.
             * @example Raspberry Pi Zero 2 W Rev 1.0
             */
            cpuModel?: string;
            /** @description Number of logical CPUs. */
            cpuCores: number;
            /**
             * Format: double
             * @description Host CPU utilization across all cores, as a percentage, averaged over the window between the server's two latest CPU readings. The readings are shared by all clients; a request less than a second after the latest one reuses its figure. The window is at most 30 seconds long: when the latest reading is older than that, the server samples for a quarter second before responding. Absent only when the host's CPU counters cannot be read or give no basis for a ratio.
             */
            cpuPercent?: number;
            /**
             * Format: int64
             * @description Total physical memory in bytes.
             */
            memTotalBytes: number;
            /**
             * Format: int64
             * @description Used physical memory in bytes (total minus available).
             */
            memUsedBytes: number;
            /**
             * Format: int64
             * @description Total bytes of the filesystem holding the appliance's data.
             */
            diskTotalBytes: number;
            /**
             * Format: int64
             * @description Used bytes of that filesystem.
             */
            diskUsedBytes: number;
            /**
             * Format: double
             * @description SoC or CPU temperature in degrees Celsius. Absent when no thermal sensor is exposed (typical off Raspberry Pi hardware).
             */
            tempCelsius?: number;
            /** @description Non-loopback network interfaces. */
            network: components["schemas"]["NetworkInterface"][];
            update?: components["schemas"]["UpdateStatus"];
        };
        /** @description The release update state: the running and newest known versions, the last check, how this appliance was installed (which decides whether it can update itself), and a one-button update in progress. */
        UpdateStatus: {
            /**
             * @description The running version.
             * @example v0.2.0
             */
            currentVersion: string;
            /** @description False for a build that names no release (such as one built as "dev"), which never checks for updates. */
            supported: boolean;
            /** @description Whether the daily check is on (`updates.check`). */
            checkEnabled: boolean;
            /**
             * @description The newest stable release found; absent before a successful check.
             * @example v0.3.0
             */
            latestVersion?: string;
            /**
             * Format: uri
             * @description The newest release's release notes; absent before a successful check.
             */
            notesUrl?: string;
            /** @description Whether latestVersion is newer than the running version. */
            available: boolean;
            /**
             * Format: date-time
             * @description When the last check finished (appliance wall clock); absent before the first check.
             */
            lastCheck?: string;
            /** @description Why the last check failed; absent after a success. */
            lastError?: string;
            /**
             * @description How the running binary was installed. `service` is the binary the installed service unit runs, from `sudo remote-mic service install`, whether it came from a tarball, a `.deb` or Homebrew; `deb` and `homebrew` are a package manager's own copy, which is never bypassed; `manual` is a binary run by hand, or one that is not the service's.
             * @enum {string}
             */
            installMethod: "service" | "deb" | "homebrew" | "manual";
            /** @description Whether `POST /system/update` can install an update here: the binary the installed service unit runs, with the root updater units installed for that same path. */
            canApply: boolean;
            /** @description How to update by hand when canApply is false. */
            upgradeHint?: string;
            /**
             * @description Where a one-button update stands. `installing` means the root updater has the release and restarts the appliance when it is done; `failed` means the last attempt failed (see phaseMessage).
             * @enum {string}
             */
            phase: "idle" | "downloading" | "installing" | "failed";
            /** @description A human-readable detail for the phase. */
            phaseMessage?: string;
        };
        /** @description One network interface and its live byte counters. */
        NetworkInterface: {
            /** @example eth0 */
            name: string;
            /**
             * @description Hardware (MAC) address; absent for interfaces without one.
             * @example dc:a6:32:00:11:22
             */
            mac?: string;
            /** @description Whether the interface is up and running. */
            up: boolean;
            /** @description Assigned IP addresses in CIDR notation. */
            addresses: string[];
            /**
             * Format: int64
             * @description Bytes received since boot.
             */
            rxBytes: number;
            /**
             * Format: int64
             * @description Bytes transmitted since boot.
             */
            txBytes: number;
            /**
             * @description What sort of link this is. `ethernet` is a physical wired interface, `wifi` a wireless one, `other` anything else (bridge, VPN tunnel, virtual). Absent when the appliance cannot tell. Later appliances may add values; clients treat an unknown value as `other`.
             * @enum {string}
             */
            kind?: "ethernet" | "wifi" | "other";
            wifi?: components["schemas"]["WifiLink"];
        };
        /** @description Wi-Fi facts for a wireless interface. Present only when `kind` is `wifi` and at least one field is known. */
        WifiLink: {
            /**
             * @description Network name; absent for a hidden network or when unreadable.
             * @example garden-ap
             */
            ssid?: string;
            /**
             * Format: int32
             * @description Received signal strength in dBm.
             * @example -52
             */
            signalDbm?: number;
            /**
             * Format: int32
             * @description Current channel frequency in MHz.
             * @example 2437
             * @example 5220
             */
            frequencyMhz?: number;
        };
    };
    responses: {
        /** @description An RFC 9457 problem detail. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The appliance is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current appliance status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplianceStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All configured devices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    provisionDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvisionDeviceRequest"];
            };
        };
        responses: {
            /** @description The device was provisioned and is being served. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description No such capture device is present on the host. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The device is already configured: by this exact id or derived name, or under another id (the host lists it but the available view hides it, for example a card index that resolves to it). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The request is well-formed but fails validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAvailableDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All detected, unconfigured devices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableDevice"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The device's configured unique name. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The named device. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    deleteDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The device's configured unique name. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The device was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    streamEvents: {
        parameters: {
            query?: {
                /** @description Event types to subscribe to, comma-separated. Absent or empty means all types. Heartbeats are always sent. */
                events?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event stream; stays open until the client disconnects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current notification snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSnapshot"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    patchConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigPatch"];
            };
        };
        responses: {
            /** @description The update was validated and persisted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigUpdateResult"];
                };
            };
            /** @description The patch is malformed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The patch is well-formed but fails validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host system information. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    postSystemRestart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restart request accepted; shutdown is initiating. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    postSystemUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The update started. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatus"];
                };
            };
            /** @description No update is available, this installation cannot update itself, update checks are turned off, or an update is already in progress. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    postSystemUpdateCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The update state after the check. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatus"];
                };
            };
            /** @description Update checks are turned off (`updates.check`), or the running build is not a release. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSystemCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current management certificate metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateInfo"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    putSystemCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificateInstallRequest"];
            };
        };
        responses: {
            /** @description The installed certificate's metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateInfo"];
                };
            };
            /** @description The certificate or key failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSystemCertificatePem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The PEM-encoded public certificate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-pem-file": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    regenerateSystemCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificateRegenerateRequest"];
            };
        };
        responses: {
            /** @description The regenerated certificate's metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateInfo"];
                };
            };
            /** @description An extra SAN entry was not a valid DNS name or IP address. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
