//go:build !skipfrontend

// Package web embeds the pre-built management web UI static assets into the Go binary.
//
// web/dist is generated by `task web:build` (tsc) and is not tracked in git, so
// this file only compiles when the assets are present on disk. Pure-Go builds
// and tests that do not need the UI use the `skipfrontend` tag, which selects
// the stub in embed_skipfrontend.go instead and needs no dist directory.
package web

import (
	"embed"
	"io/fs"
)

// distEmbed contains the compiled frontend assets from the dist directory. It is
// unexported so the package's exported surface is exactly DistFS(), matching the
// skipfrontend stub in embed_skipfrontend.go.
//
//go:embed dist
var distEmbed embed.FS

// DistFS returns an fs.FS rooted at the dist directory.
func DistFS() (fs.FS, error) {
	return fs.Sub(distEmbed, "dist")
}
